#!/bin/bash
CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda create -n cgraphs_env python
conda activate cgraphs_env
conda config --add channels conda-forge
conda install -c conda-forge mdanalysis
conda deactivate