#!/bin/bash
# ========================================
# Don't change this part
CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda activate py312

LOGFILE=output.log
echo "$(date '+%Y-%m-%d %H:%M:%S'): Starting pKa calculation script..." >> "$LOGFILE"

# ========================================
# Under this line come the parameters to run the script with

#path to the psf file:
PSF_FILE='/Users/evabertalan/Documents/projects/JSR1_pka_proj/scripts/example_files/read_protein_membrane_7_9cis_y126a_3_2x.psf'

#path to the dcd files. Files can be defined individually listed after each other. Or multiple files selected using the glob wildcards.
DCD_FILES='/Users/evabertalan/Documents/projects/JSR1_pka_proj/scripts/example_files/9cis_y126a_last_20frames_pbc*.dcd' 

#path to the output folder, in this folder will be the calculation results saved
OUTPUT_FOLDER='/Users/evabertalan/Desktop/test'


python3 -m pka_from_traj "$PSF_FILE" "$DCD_FILES" --output_folder "$OUTPUT_FOLDER" --plot >> "$LOGFILE" 2>&1



# =====================================
# Don't change this part
echo "$(date '+%Y-%m-%d %H:%M:%S'): Finished pKa calculation" >> "$LOGFILE"
conda deactivate